#!/usr/bin/python3
import sys, os, pyairtable, re, datetime
from columnar import columnar
from dotenv import load_dotenv, dotenv_values
from pyairtable.formulas import match
from click import style
import poclasses

command = ""
patterns = [
        ('.*:\ ?\d{4}-\d{2}-\d{2}', lambda text: style(text, bg='blue', fg='black', bold=True)),
        ('Qty:.+', lambda text: style(text, bg='black', fg='bright_blue', bold=True)),
        ('PO Number:.+', lambda text: style(text, bg='magenta', fg='black', bold=False)),
        ('.*', lambda text: style(text, bg='black', fg='white')),
]

def printhelp():
    print("Available commands:")
    print("    atcli getpo <po number> <width of table>")
    print("    atcli updatefab <po number>-<item number>+<qty> <po number>-<item number>+<qty> ...")
    print("          for e.g. 'atcli updatefab L99998-A2+4 L99997-2+3'")

def printitem(item):
    outputstring = ''
    fields = item['fields']
    numCols = 5
    counter = 0
    sortedfields = sorted(fields, key=str.lower)
    row = []
    rows = []
    for key in sortedfields:
        val = fields[key]
        fieldstring = key + ': ' + str(val).replace('\n', '')
        if counter == (numCols-1):
            counter = 0
            row.append(fieldstring)
            rows.append(row[:])
            # print(row)
            row = [] 
        else:
            row.append(fieldstring)
            # print(row)
            counter += 1
        # fieldstring = key + ': ' + str(val)
        # fieldstring = fieldstring[0:45].replace('\n', '')
        # outputstring += fieldstring + ' |'
        # if counter == (numCols-1):
            # counter = 0
            # outputstring += '\n\n'
        # else:
            # counter += 1
    
    output = columnar(
            rows, headers=None, patterns=patterns, 
            row_sep=style('-',bg='black',fg='white'), 
            column_sep=style('|', bg='black', fg='white'),
            # max_column_width=50,
            terminal_width=termwidth,
            # min_column_width=9,
            )
    print(output)
    # print(rows)
    return output


try:
    command = sys.argv[1] 
except IndexError:
    printhelp()
else:
    if command != 'help':
        load_dotenv()
        print("Connecting to airtable...")
        key = os.environ['AIRTABLEKEY']
        baseid = os.environ['AIRTABLEBASEID']
        table = pyairtable.Table(key, baseid, 'Table 1')

if command == "getpo":
    try:
        termwidth = int(sys.argv[3])
    except IndexError: 
        termwidth = 240
    try:
        which = sys.argv[2]
        print(which)
        formula = "FIND('%s' , {PO Number})" % which
        output = table.all(formula = formula)
        for item in output:
            print('     ----     ')
            printitem(item)
    except IndexError: 
        print("No PO number specified. Please specify a PO number.")

elif command == "updatefab":
    which = sys.argv[2:]
    for postr in which:
        ponum = postr.split('-')[0]
        itemnumqty = postr.split('-')[1]
        qty = itemnumqty.split('+')[1]
        itemnum = itemnumqty.split('+')[0]
        formula = "IF(AND({PO Number Regex}='%s', {Item No.}='%s'), 1, 0)" % (ponum, itemnum)
        # formula = "IF({PO Number}='%s', 1, 0)" % (ponum)
        records = table.all(formula = formula, fields = ['Fabrication Done?', 'PO Number ITEM', 'Completion Log', 'Qty Completed'])
        for item in records:
            itemid = item['id']
            fields = item['fields']
            try:
                qty_completed = int(fields['Qty Completed'])
            except KeyError:
                qty_completed = 0
            
            try:
                completion_log = fields['Completion Log']
            except KeyError:
                completion_log = ''

            datestring = datetime.datetime.now().strftime('%Y-%m-%d')
            qty_completed = qty_completed + int(qty)

            completion_log += datestring
            completion_log += ' :  '
            completion_log += str(qty)
            completion_log += '\n'
            print(qty_completed)
            fields['Fabrication Done?'] = True
            fields['Qty Completed'] = qty_completed
            fields['Completion Log'] = completion_log
            fields['Fabrication Date Done'] = datetime.datetime.now().strftime('%Y-%m-%d')
            print(item['fields'])
            fields.pop('PO Number ITEM')
            table.update(itemid, fields)
            # print(datetime.datetime.now())

elif command == "help" or command == "--help":
    printhelp()
